### ISSUE TITLE
Bypass style limit not working

### ISSUE THREAD

**Issue by axemwa** [spyproof/NicknameManager#3]
I set the bypass style limit permission for default group to true, but it won't allow be to set this &cS&6h&eA&an&bO
as this message appears
![image](https://user-images.githubusercontent.com/37608633/45001332-59a64d80-b00b-11e8-9f96-5fdecc9c8799.png)
using 1.12.2

**Comment by axemwa** [comment]
`# The absolute max length is 255 characters, including colour characters!
# Specifying any larger number in this category will be ignored.
maxlength:
  # The max length of a nickname including the colour characters
  # Example: &1&lNotch = 9
  withColour: 48
  # The max length of a nickname excluding the colour characters
  # Example: &1&lNotch = 5
  withoutColour: 24

# Maximum colors per nickname, there are 16 colors
maxcolors: 16

# Maximum effects per nickname, there are 5 effects (bold, strikethrough, underline, italic, magic)
maxeffects: 16

# Decide if players need to accept the rules first
mustAcceptRules: true

# Player nicknames will also appear in the tab list.
setTabListName: true

# Banned nicknames with regex syntax (not case sensitive)
blacklist:
- '[o0O]wn[e3]r' # owner
- 'f[o0O]und[e3]r' # founder
- '[Aa@]dm[i1]n' # admin
- 'm[o0O]d([e3]r[a4]t[o0]r)?' # mod
- 'h[e3]lp[e3]r' # helper
- 'n[i1]g+[e3]r' # nigger
- 'n[i1]g+[a4]r*' # nigga
- 'f[a4]g+[o0]t' # faggot
- 'r[a4]p[i1]st' # rapist
- 'n[a4]z[i1]' # nazi
- 'sh[i1]t' # shit
- 'y[o0O]utub[e3]r?' # youtuber
- 'str[e3][a4]m([e3]r)?' # streamer
- 'n[o0O]tch' # notch
- '[cC]reat[oe][Rr]' #CreatoR

# Cooldowns for changing your nickname
# Format: years(y), months(mo), weeks(w), days(d), hours(h), minutes(m), seconds(s)
cooldown:
  default: 1mo # Default cooldown
  VIP: 1w # If player has the permission 'nicknames.cooldown.VIP1'
  Donator: 1d # If player has the permission 'nicknames.cooldown.VIP2'

# Choose to save player data in YML files (local) or in MySQL (database)
storage: YML

# Database to store the synced nicknames, if the storage is MySQL
mysql:
  host: 127.0.0.1
  port: 3306
  database: Nicknames
  user: Derp
  password: MyUberPassWord`

**Comment by axemwa** [comment]
[https://pastebin.com/giEqj22B](url)

**Comment by spyproof** [comment]
You still require permissions for each color/effect. The bypass allows toy to bypass the amount of colors/effects you can have in your name.

**Comment by axemwa** [comment]
ah sorry my bad I haven't read down that far yet in the permissions section of the wiki thanx for ur help :)

**Comment by axemwa** [comment]
I suggest adding nickmanager.colors.* so they don't have to be set individually as I tried adding nickmanager.colors.* in luckperms and didn't seem to work

**Comment by spyproof** [comment]
There was a typo, its suppose to be `nickmanager.colours`. Fixed in the wiki.

**Comment by axemwa** [comment]
Ah I see, so all color permissions needs to have "color." changed to "colour." now?
Also did you include the .* for all colours etc will this work, if so I sugegst adding it to the permissions list :)

**Comment by axemwa** [comment]
also might wanna change this nickmanager.bypass.colorlimit to this **nickmanager.bypass.colourlimit**
